# Generated by Django 5.1.4 on 2025-01-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_variacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variacao', 'verbose_name_plural': 'Variacoes'},
        ),
    ]
